route:
  group_by: [Alertname]
  # Send all notifications to me.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: aftabali025@gmail.com
    from: aftabali025@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "aftabali025@gmail.com"
    auth_identity: "aftabali025@gmail.com"
    auth_password: "xxxxxxxxxxxxxxx"
